version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo installing maven
      - apt-get update -y
      - apt-get install -y maven
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
      - mv target/rating-data-service-0.0.1-SNAPSHOT.war rating-data-service-0.0.1-SNAPSHOT.jar
artifacts:
  files:
    - rating-data-service-0.0.1-SNAPSHOT.jar
    - .ebextentions/**/*
