version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo installing maven
      - yum update -y
      - yum install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn clean
      - mvn package -DskipTests
artifacts:
  files:
    - target/rating-data-service-1.0-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes